//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("TDConfiguration", Namespace ="", IsNullable=false)]
public partial class TDConfiguration {
    
    private TDConfigurationBinding bindingField;
    
    private string endpointAddressField;
    
    private int timerIntervalField;
    
    private string userIDField;
    
    /// <remarks/>
    public TDConfigurationBinding Binding {
        get {
            return this.bindingField;
        }
        set {
            this.bindingField = value;
        }
    }
    
    /// <remarks/>
    public string EndpointAddress {
        get {
            return this.endpointAddressField;
        }
        set {
            this.endpointAddressField = value;
        }
    }
    
    /// <remarks/>
    public int TimerInterval {
        get {
            return this.timerIntervalField;
        }
        set {
            this.timerIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string UserID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TDConfigurationBinding {
    
    private int closeTimeoutField;
    
    private int openTimeoutField;
    
    private int receiveTimeoutField;
    
    private int sendTimeoutField;
    
    private long maxBufferPoolSizeField;
    
    private long maxReceivedMessageSizeField;
    
    private TDConfigurationBindingReaderQuotas readerQuotasField;
    
    /// <remarks/>
    public int CloseTimeout {
        get {
            return this.closeTimeoutField;
        }
        set {
            this.closeTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public int OpenTimeout {
        get {
            return this.openTimeoutField;
        }
        set {
            this.openTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public int ReceiveTimeout {
        get {
            return this.receiveTimeoutField;
        }
        set {
            this.receiveTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public int SendTimeout {
        get {
            return this.sendTimeoutField;
        }
        set {
            this.sendTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public long MaxBufferPoolSize {
        get {
            return this.maxBufferPoolSizeField;
        }
        set {
            this.maxBufferPoolSizeField = value;
        }
    }
    
    /// <remarks/>
    public long MaxReceivedMessageSize {
        get {
            return this.maxReceivedMessageSizeField;
        }
        set {
            this.maxReceivedMessageSizeField = value;
        }
    }
    
    /// <remarks/>
    public TDConfigurationBindingReaderQuotas ReaderQuotas {
        get {
            return this.readerQuotasField;
        }
        set {
            this.readerQuotasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TDConfigurationBindingReaderQuotas {
    
    private int maxDepthField;
    
    private int maxStringContentLengthField;
    
    private int maxArrayLengthField;
    
    private int maxBytesPerReadField;
    
    private int maxNameTableCharCountField;
    
    /// <remarks/>
    public int MaxDepth {
        get {
            return this.maxDepthField;
        }
        set {
            this.maxDepthField = value;
        }
    }
    
    /// <remarks/>
    public int MaxStringContentLength {
        get {
            return this.maxStringContentLengthField;
        }
        set {
            this.maxStringContentLengthField = value;
        }
    }
    
    /// <remarks/>
    public int MaxArrayLength {
        get {
            return this.maxArrayLengthField;
        }
        set {
            this.maxArrayLengthField = value;
        }
    }
    
    /// <remarks/>
    public int MaxBytesPerRead {
        get {
            return this.maxBytesPerReadField;
        }
        set {
            this.maxBytesPerReadField = value;
        }
    }
    
    /// <remarks/>
    public int MaxNameTableCharCount {
        get {
            return this.maxNameTableCharCountField;
        }
        set {
            this.maxNameTableCharCountField = value;
        }
    }
}
