//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TowerDefenseEntities : DbContext
    {
        public TowerDefenseEntities()
            : base("name=TowerDefenseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TD_Player> TD_Player { get; set; }
        public virtual DbSet<TD_Game> TD_Game { get; set; }
        public virtual DbSet<TD_GameStep> TD_GameStep { get; set; }
    }
}
