//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Game
    {
        public int GameId { get; set; }
        public string GameState { get; set; }
        public Nullable<int> GameMapId { get; set; }
        public int StateCount { get; set; }
        public string WinnerUser { get; set; }
        public string CalledUser { get; set; }
    }
}
