//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_GameStep
    {
        public int StepId { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public string EntityType { get; set; }
    }
}
